---
sync:
    port: {{ config.sync.port }}

peers:
    - "aenode://pp$2CL6TSL9Lgfz63P8n4juyNcaw4RDzKzvaPKvKHBnwMerkPBW3n@35.156.63.78:3015"
    - "aenode://pp$JF7parbPeVo5qyg3oUJerRHGDCL5Qym6nXJ1ZrMpenXgNaDVJ@54.202.138.99:3015"
    - "aenode://pp$6hTca1U9VtgLh6ZxcsEzVNxV4vVPMRGKzsS9w1yJaHgufJvaz@52.221.60.178:3015"

keys:
    dir: {{ config.keypair.dir }}
    password: "{{ config.keypair.password }}"

http:
    external:
        port: {{ config.http.external.port }}
    internal:
        listen_address: 0.0.0.0
        port: {{ config.http.internal.port }}
    debug: true

websocket:
    internal:
        listen_address: {{ config.websocket.internal.listen_address }}
        port: {{ config.websocket.internal.port }}

mining:
    autostart: true
    beneficiary: {{ config.mining.beneficiary }}
    expected_mine_rate: 15000
    cuckoo:
        miner:
            executable: mean16s-generic
            extra_args: ""
            node_bits: 16

chain:
    persist: {{ config.chain.persist | bool | lower }}
    db_path: {{ config.chain.db_path }}

logging:
    level: {{ config.logging.level }}

metrics:
    # StatsD server and port
    host: 127.0.0.1
    port: 8125
